package br.ufscar;

public enum ErrosSemanticos {
    IDENTIFICADOR_EXISTENTE,
    IDENTIFICADOR_INEXISTENTE,
    TIPO_INEXISTENTE,
    ATRIBUICAO_INCOMPATIVEL,
    PARAMETROS_INCOMPATIVEIS,
    ESCOPO_INVALIDO
}
