package br.ufscar;

public enum TipoAl {
    INTEIRO,
    LITERAL,
    REAL,
    LOGICO,
    CADEIA,
    PROCEDIMENTO,
    FUNCAO,
    REGISTRO,
    PONTEIRO_INTEIRO,
    PONTEIRO_REAL,
    PONTEIRO_LITERAL,
    PONTEIRO_LOGICO,
    PONTEIRO_REGISTRO,
    ENDERECO_INTEIRO,
    ENDERECO_REAL,
    ENDERECO_LOGICO,
    ENDERECO_LITERAL,
    ENDERECO_REGISTRO,
    TIPO,
    INVALIDO
}
